// Code generated by goctl. DO NOT EDIT!

package genModel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	homestayOrderFieldNames          = builder.RawFieldNames(&HomestayOrder{})
	homestayOrderRows                = strings.Join(homestayOrderFieldNames, ",")
	homestayOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(homestayOrderFieldNames, "`runoob_id`", "`create_time`", "`update_time`"), ",")
	homestayOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(homestayOrderFieldNames, "`runoob_id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheLooklookOrderHomestayOrderRunoobIdPrefix = "cache:looklookOrder:homestayOrder:runoobId:"
)

type (
	homestayOrderModel interface {
		Insert(ctx context.Context, data *HomestayOrder) (sql.Result, error)
		FindOne(ctx context.Context, runoobId int64) (*HomestayOrder, error)
		Update(ctx context.Context, data *HomestayOrder) error
		Delete(ctx context.Context, runoobId int64) error
	}

	defaultHomestayOrderModel struct {
		sqlc.CachedConn
		table string
	}

	HomestayOrder struct {
		RunoobId       int64        `db:"runoob_id"`
		RunoobTitle    string       `db:"runoob_title"`
		RunoobAuthor   string       `db:"runoob_author"`
		SubmissionDate sql.NullTime `db:"submission_date"`
	}
)

func newHomestayOrderModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultHomestayOrderModel {
	return &defaultHomestayOrderModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`homestay_order`",
	}
}

func (m *defaultHomestayOrderModel) Insert(ctx context.Context, data *HomestayOrder) (sql.Result, error) {
	looklookOrderHomestayOrderRunoobIdKey := fmt.Sprintf("%s%v", cacheLooklookOrderHomestayOrderRunoobIdPrefix, data.RunoobId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, homestayOrderRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RunoobTitle, data.RunoobAuthor, data.SubmissionDate)
	}, looklookOrderHomestayOrderRunoobIdKey)
	return ret, err
}

func (m *defaultHomestayOrderModel) FindOne(ctx context.Context, runoobId int64) (*HomestayOrder, error) {
	looklookOrderHomestayOrderRunoobIdKey := fmt.Sprintf("%s%v", cacheLooklookOrderHomestayOrderRunoobIdPrefix, runoobId)
	var resp HomestayOrder
	err := m.QueryRowCtx(ctx, &resp, looklookOrderHomestayOrderRunoobIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `runoob_id` = ? limit 1", homestayOrderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, runoobId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHomestayOrderModel) Update(ctx context.Context, data *HomestayOrder) error {
	looklookOrderHomestayOrderRunoobIdKey := fmt.Sprintf("%s%v", cacheLooklookOrderHomestayOrderRunoobIdPrefix, data.RunoobId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `runoob_id` = ?", m.table, homestayOrderRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.RunoobTitle, data.RunoobAuthor, data.SubmissionDate, data.RunoobId)
	}, looklookOrderHomestayOrderRunoobIdKey)
	return err
}

func (m *defaultHomestayOrderModel) Delete(ctx context.Context, runoobId int64) error {
	looklookOrderHomestayOrderRunoobIdKey := fmt.Sprintf("%s%v", cacheLooklookOrderHomestayOrderRunoobIdPrefix, runoobId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `runoob_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, runoobId)
	}, looklookOrderHomestayOrderRunoobIdKey)
	return err
}

func (m *defaultHomestayOrderModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheLooklookOrderHomestayOrderRunoobIdPrefix, primary)
}

func (m *defaultHomestayOrderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `runoob_id` = ? limit 1", homestayOrderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultHomestayOrderModel) tableName() string {
	return m.table
}
